git clone https://github.com/Activiti/activiti-build.git
git clone https://github.com/Activiti/Activiti.git
git clone https://github.com/Activiti/activiti-cloud-build.git
git clone https://github.com/Activiti/activiti-cloud-service-common.git
git clone https://github.com/Activiti/activiti-cloud-runtime-bundle-service.git
git clone https://github.com/Activiti/activiti-cloud-query-service.git
git clone https://github.com/Activiti/activiti-cloud-audit-service.git
git clone https://github.com/Activiti/activiti-cloud-form-runtime-service.git
git clone https://github.com/Activiti/activiti-cloud-process-model-service.git
git clone https://github.com/Activiti/activiti-cloud-connectors.git
git clone https://github.com/Activiti/activiti-cloud-registry.git
git clone https://github.com/Activiti/activiti-cloud-gateway.git
git clone https://github.com/Activiti/activiti-cloud-sso-idm.git
git clone https://github.com/Activiti/activiti-cloud-query.git
git clone https://github.com/Activiti/activiti-cloud-audit.git
git clone https://github.com/Activiti/activiti-cloud-audit-mongodb.git
git clone https://github.com/Activiti/activiti-form-runtime.git
git clone https://github.com/Activiti/activiti-cloud-runtime-bundle.git
git clone https://github.com/Activiti/activiti-cloud-examples.git