version: '2'
services:
	# We decided to configure our runtime bundle against a PostgreSQL instance
  rb-postgres:
    image: postgres
    ports:
     - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=activitidb
    networks:
      - infrastructure
# we will join the infrastructure network defined by the infrastructure docker compose.
networks:
  infrastructure:
    external:
      name: docker_default
